language: rust
sudo: false

os:
- linux
- osx

script:
- rustup component add rustfmt
- cargo build --verbose
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cargo test --verbose; fi
- cargo fmt -- --check
